// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bucket struct {
	BucketID  int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Key       string
	Name      string
	CredID    string
	Record    string
	Cipher    string
}

type File struct {
	FileID        int64
	BucID         int64
	CreatedAt     pgtype.Timestamptz
	Valid         bool
	DataFile      string
	FileUuid      pgtype.UUID
	MetaFile      string
	DigestFile    string
	UploadID      string
	BasePath      string
	FileInfo      string
	FileInfoNonce string
	DataFileSize  int64
}
